import { File } from "../Types";
import sampleImage from "../assets/test/test.jpg";
import sampleImage2 from "../assets/test/test2.jpg";
import sampleImage3 from "../assets/test/test3.jpg";
import sampleImage4 from "../assets/test/test4.jpg";
const sampleTags = [
  "Finance",
  "Marketing",
  "HR",
  "Project",
  "Confidential",
  "Public",
  "Finankol",
  "Markisidei",
  "Kurksi",
  "NMcnsue",
  "Sakhat-Secret",
  "What",
  "Poeiure",
  "Jdurs",
  "MR",
  "Csduir",
  "When",
];

const getRandomTags = () => {
  const shuffled = sampleTags.sort(() => 0.5 - Math.random()); // Shuffle array
  return shuffled.slice(0, Math.floor(Math.random() * shuffled.length + 1)); // Get sub-array of tags
};

export const files: File[] = [
  {
    id: 1,
    name: "Report and Other Stuff.pdf",
    image: sampleImage,
    type: "pdf",
    storageUsed: "1.7 MB",
    location: "Server A",
    owner: "Alice Johnson",
    created: "2023-03-01",
    lastModified: "2023-04-20",
    downloadPermission: "Editable",
    link: "https://example.com/file1",
    size: "1.5 MB",
    tags: getRandomTags(),
    description: "Annual financial report and related documents.",
  },
  {
    id: 2,
    name: "Budget.xlsx",
    image: sampleImage2,
    type: "xlsx",
    storageUsed: "220 KB",
    location: "Server B",
    owner: "Bob Smith",
    created: "2023-02-15",
    lastModified: "2023-04-19",
    downloadPermission: "Read-only",
    link: "https://example.com/file2",
    size: "200 KB",
    tags: getRandomTags(),
    description: "Budget calculations for the 2023 fiscal year.",
  },
  {
    id: 3,
    name: "Present.pptx",
    image: sampleImage3,
    type: "pptx",
    storageUsed: "3.5 MB",
    location: "Cloud Storage C",
    owner: "Charlie Daniels",
    created: "2023-01-10",
    lastModified: "2023-04-18",
    downloadPermission: "View only",
    link: "https://example.com/file3",
    size: "3.2 MB",
    tags: getRandomTags(),
    description: "Presentation for Q1 results.",
  },
  {
    id: 4,
    name: "Report and Other Stuff.pdf",
    image: sampleImage4,
    type: "pdf",
    storageUsed: "1.7 MB",
    location: "Server A",
    owner: "Alice Johnson",
    created: "2023-03-01",
    lastModified: "2023-04-20",
    downloadPermission: "Editable",
    link: "https://example.com/file1",
    size: "1.5 MB",
    tags: getRandomTags(),
    description: "Annual financial report and related documents.",
  },
  {
    id: 5,
    name: "Budget.xlsx",
    image: sampleImage,
    type: "xlsx",
    storageUsed: "220 KB",
    location: "Server B",
    owner: "Bob Smith",
    created: "2023-02-15",
    lastModified: "2023-04-19",
    downloadPermission: "Read-only",
    link: "https://example.com/file2",
    size: "200 KB",
    tags: getRandomTags(),
    description: "Budget calculations for the 2023 fiscal year.",
  },
  {
    id: 6,
    name: "Present.pptx",
    image: sampleImage2,
    type: "pptx",
    storageUsed: "3.5 MB",
    location: "Cloud Storage C",
    owner: "Charlie Daniels",
    created: "2023-01-10",
    lastModified: "2023-04-18",
    downloadPermission: "View only",
    link: "https://example.com/file3",
    size: "3.2 MB",
    tags: getRandomTags(),
    description: "Presentation for Q1 results.",
  },
  {
    id: 7,
    name: "Report and Other Stuff.pdf",
    image: sampleImage3,
    type: "pdf",
    storageUsed: "1.7 MB",
    location: "Server A",
    owner: "Alice Johnson",
    created: "2023-03-01",
    lastModified: "2023-04-20",
    downloadPermission: "Editable",
    link: "https://example.com/file1",
    size: "1.5 MB",
    tags: getRandomTags(),
    description: "Annual financial report and related documents.",
  },
  {
    id: 8,
    name: "Budget.xlsx",
    image: sampleImage4,
    type: "xlsx",
    storageUsed: "220 KB",
    location: "Server B",
    owner: "Bob Smith",
    created: "2023-02-15",
    lastModified: "2023-04-19",
    downloadPermission: "Read-only",
    link: "https://example.com/file2",
    size: "200 KB",
    tags: getRandomTags(),
    description: "Budget calculations for the 2023 fiscal year.",
  },
  {
    id: 9,
    name: "Present.pptx",
    image: sampleImage,
    type: "pptx",
    storageUsed: "3.5 MB",
    location: "Cloud Storage C",
    owner: "Charlie Daniels",
    created: "2023-01-10",
    lastModified: "2023-04-18",
    downloadPermission: "View only",
    link: "https://example.com/file3",
    size: "3.2 MB",
    tags: getRandomTags(),
    description: "Presentation for Q1 results.",
  },
  {
    id: 10,
    name: "Report and Other Stuff.pdf",
    image: sampleImage2,
    type: "pdf",
    storageUsed: "1.7 MB",
    location: "Server A",
    owner: "Alice Johnson",
    created: "2023-03-01",
    lastModified: "2023-04-20",
    downloadPermission: "Editable",
    link: "https://example.com/file1",
    size: "1.5 MB",
    tags: getRandomTags(),
    description: "Annual financial report and related documents.",
  },
  {
    id: 11,
    name: "Budget.xlsx",
    image: sampleImage3,
    type: "xlsx",
    storageUsed: "220 KB",
    location: "Server B",
    owner: "Bob Smith",
    created: "2023-02-15",
    lastModified: "2023-04-19",
    downloadPermission: "Read-only",
    link: "https://example.com/file2",
    size: "200 KB",
    tags: getRandomTags(),
    description: "Budget calculations for the 2023 fiscal year.",
  },
  {
    id: 12,
    name: "Present.pptx",
    image: sampleImage4,
    type: "pptx",
    storageUsed: "3.5 MB",
    location: "Cloud Storage C",
    owner: "Charlie Daniels",
    created: "2023-01-10",
    lastModified: "2023-04-18",
    downloadPermission: "View only",
    link: "https://example.com/file3",
    size: "3.2 MB",
    tags: getRandomTags(),
    description: "Presentation for Q1 results.",
  },
];
